In [11]:
import numpy 

In [12]:
myList=[20,30,40]

In [13]:
type(myList)

list

In [17]:
myList2=numpy.array(myList)

In [18]:
type(myList2)

numpy.ndarray

In [26]:
matrixList=[list(range(10,40,10)),
            list(range(40,70,10)),
            list(range(70,100,10))]

In [27]:
matrixList

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [28]:
matrixArray=numpy.array(matrixList)

In [29]:
matrixArray

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

ARANGE () METODU:BELİRTİLEN ARALIKTA VE BELİRTİLEN STEP SİZE KADAR DİZİ OLUŞTURUR
ARANGE(BAŞLANGIÇ,BİTİŞ,ATLAMA SAYISI)


In [34]:
numpy.arange(0,20,5)

array([ 0,  5, 10, 15])

ZEROS() METODU:0 İÇEREN DİZİ OLUŞTURUR
ZEROS(SIFIR SAYISI)


In [32]:
numpy.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

EĞER BU METOT KULLANILARAK BİR ÇOK BOYUTLU DİZİ YANİ MATRİX OLUŞTURULMAK İSTENİRSE
numpy.zeros((satır sayısı,sütun sayısı))


In [35]:
numpy.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

ONES() METODU

In [38]:
numpy.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

LINSPACE() METODU

 numpy.linspace(başlangıç,bitiş,sayı adeti)-->burada belirtilen aralıkta belirtilen sayı adeti kadar sayıyı eşit aralıklarla oluşturup bu değerleri bir diziye atar

In [43]:
numpy.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

EYE() METODU-->BU METOT İLE OLUŞTURULAN MATRİSLERİ LİNEER CEBİRDE GÖRMÜŞTÜK

In [44]:
numpy.eye(3)#parametresi aslında 3*3 matrisine karşılık gelmektedir

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
numpy.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

RANDOM

In [52]:
numpy.random.randn(3)#bir numpy dizisi döndürür-->şuan tek boyutlı

array([ 0.25823143,  1.42537309, -1.76391275])

In [53]:
numpy.random.randn(3,3)#şimdi çok boyutlu bir dizi oluşturur random olarak

array([[-1.22702176, -0.61981513,  0.02695502],
       [ 1.91805957,  0.09701231,  1.49769042],
       [-1.58208069, -0.62089155,  2.74148244]])

In [55]:
numpy.random.randint(1,20)#bu sadece rastgelebir int değer döndürür
#belirtilen aralıkta 
#buradaki aralıkta başlangıç dahil fakat bitiş dahil değildir

6

In [56]:
#eğer randint metodunu kullanarak rasgele tamsayılardan oluşan bir array 
#tanımalamak istersek
numpy.random.randint(1,20,10)

array([ 4, 16,  1,  9,  1,  1, 11, 12,  8, 19])

In [57]:
myNumpyArray=numpy.arange(20)

In [61]:
type(myNumpyArray)

numpy.ndarray

ARRAY METHODS

In [81]:
arrayRegular=numpy.arange(0,30)#düzenli ifadelerle oluşturulmuş array
arrayRandom=numpy.random.randint(0,100,30)#rastgele ifadelerle oluşturulmuş array

In [82]:
arrayRegular


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [83]:
arrayRandom

array([16, 76, 29, 74, 77, 81, 91, 50, 18, 92, 32, 16, 47, 69, 94, 66,  1,
       28, 84, 11, 25, 75, 18, 76, 14, 95, 34, 16, 49, 36])

In [84]:
#eğer herhangi bir arrayi parçalayarak yeni arrayler oluşturmak istersek 
#reshape:yeniden şekillendirme 
#burada parametre olarak girilen array eleman sayısının arrayRegular 
#tarafından karşılanabilecek sayıda olması gerekir yoksa error alırızı

In [86]:
arrayRegular.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [87]:
arrayRegular.reshape(6,5)#dizi bu metotla yeniden biçimlendirilebilinir

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [88]:
arrayRandom.max()#bu metot ile dizinin max elemanı yazdırılır 

95

In [89]:
arrayRandom.min()#bu metot ile dizi içerisindeki en küçük değer getirilir

1

In [91]:
#eğer max ve min elemanların indexlerini öğrenmek istiyorsak
arrayRandom.argmax()


25

In [92]:
arrayRandom.argmin()

16

In [93]:
#eğer dizinin biçimini yazdırmak istersek
arrayRandom.shape

(30,)

# İNDEKSLER


In [120]:
myList=numpy.arange(0,21)

In [121]:
myList

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [122]:
myList[5]

5

SLICING(DİLİMLEME)

In [123]:
myList[3:12]#başlangıç dahil bitiş dahil değil

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [124]:
#dilimleme işlemi listelerdeki gibidir fakat dilimlediğimizi dilimi başka bir değişkene atayıp o değişken üzerinden bir 
#bir değişiklik gerçekleştirirsek bu değişiklik asıl diziye de yasıtılır bunu engellemek için dizinin kopyasını oluşturur 
#ve bu kopya üzerinde dilimleme işlemimi gerçekleştiririz bu şeklide yaptığımı değişkilikler asıl diziye yansıtılmaz


In [125]:
myListSlicing=myList[0:12]

In [126]:
myListSlicing

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [127]:
#myListSlicing[:]=200
#myList -->asıl dizi üzerindeki değişimi engellemek için kopyası oluşturulur

In [129]:
myListCopy=myList.copy()

In [130]:
myListCopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [131]:
myListSlicing2=myListCopy[0:12]
myListSlicing2[:]=700

In [134]:
myListSlicing2

array([700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700])

In [135]:
myListCopy

array([700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700,  12,
        13,  14,  15,  16,  17,  18,  19,  20])

In [136]:
myList

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

MATRIX INDEX

In [9]:
import numpy

In [10]:
myList=[list(range(10,40,10)),list(range(20,50,10)),list(range(40,70,10))]

In [11]:
myList

[[10, 20, 30], [20, 30, 40], [40, 50, 60]]

In [12]:
arrayList=numpy.array(myList)

In [13]:
arrayList

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [16]:
arrayList[0][2]#matris için (1,3) aslında 

30

In [18]:
arrayList[1,2]#=====arrayList[1][2] aynıdır

40

Slicing

In [24]:
arrayList[0:,2]

array([30, 40, 60])

In [31]:
newList=[list(range(0,5)),list(range(5,10)),list(range(10,15)),list(range(15,20)),list(range(20,25))]


In [32]:
newArray=numpy.array(newList)

In [33]:
newArray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
newArray[[1,3,2]]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14]])

# OPERASYONLAR

In [37]:
new_a_array=numpy.random.randint(1,100,20)

In [38]:
new_a_array

array([73, 39, 33, 31, 15,  8,  4, 61, 68, 10, 78, 64, 10, 60, 96, 96,  8,
       68, 22, 59])

In [39]:
new_a_array>25

array([ True,  True,  True,  True, False, False, False,  True,  True,
       False,  True,  True, False,  True,  True,  True, False,  True,
       False,  True])

In [43]:
new_a_array

array([73, 39, 33, 31, 15,  8,  4, 61, 68, 10, 78, 64, 10, 60, 96, 96,  8,
       68, 22, 59])

In [44]:
bool_array=new_a_array>25

In [45]:
bool_array

array([ True,  True,  True,  True, False, False, False,  True,  True,
       False,  True,  True, False,  True,  True,  True, False,  True,
       False,  True])

In [46]:
bool_array[0]

True

In [47]:
new_a_array[bool_array]

array([73, 39, 33, 31, 61, 68, 78, 64, 60, 96, 96, 68, 59])

In [48]:
new_a_array[new_a_array>25]

array([73, 39, 33, 31, 61, 68, 78, 64, 60, 96, 96, 68, 59])

In [49]:
newArray=numpy.arange(0,24)

In [50]:
newArray+newArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [51]:
newArray*newArray

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [52]:
newArray-newArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [53]:
numpy.sqrt(newArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [55]:
numpy.max(newArray)

23

In [56]:
numpy.min(newArray)

0