In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
liste=["Gamze",12,True,12.3]

In [5]:
print(type(liste[0]))
print(type(liste[1]))
print(type(liste[2]))
print(type(liste[3]))

<class 'str'>
<class 'int'>
<class 'bool'>
<class 'float'>


In [6]:
#listedeki elemanlar birbirinden farklı türde olabilirler fakat bu durum numpy arrayleri için geçerli değildir

In [7]:
arr1=np.array(liste)

In [11]:
print(type(arr1[0]))
print(type(arr1[1]))
print(type(arr1[2]))
print(type(arr1[3]))
#buradaki hiyerarşi şu şekilde :
#str>float>int>bool şeklindedir

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [12]:
 arr2=np.array([1,2,3])

In [14]:
type(arr2)
#numpy.ndarray şeklinde n boyutlu array anlamına gelmektedir


numpy.ndarray

In [17]:
zerosarr=np.zeros([5,5])#numpy da floatta .0 yazılmaz . yazılır sadece 

In [18]:
zerosarr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
onesarr=np.ones((5,5))

In [20]:
onesarr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
fullarr=np.full((5,5),3)#model oluşturmada kullanılır 

In [24]:
fullarr

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [26]:
np.random.randint(0,10,(10,10))

array([[2, 4, 9, 8, 2, 1, 2, 9, 7, 7],
       [7, 6, 7, 8, 6, 5, 0, 3, 2, 1],
       [1, 5, 4, 5, 9, 1, 2, 3, 1, 4],
       [9, 3, 4, 2, 6, 6, 9, 4, 6, 1],
       [7, 3, 8, 4, 5, 4, 5, 9, 3, 7],
       [2, 3, 5, 4, 8, 2, 5, 0, 0, 5],
       [9, 0, 4, 6, 4, 3, 6, 2, 1, 4],
       [6, 4, 9, 9, 6, 9, 9, 0, 1, 8],
       [4, 1, 0, 6, 3, 6, 4, 0, 9, 8],
       [5, 4, 4, 0, 8, 1, 8, 1, 6, 0]])

In [29]:
np.eye(5)#birim matris oluşturuyor

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.eye(100)#üç noktaya dikkat

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [34]:
np.linspace(0,100,20)#belirtilen aralıktaki sayıları belirtilen sayı adeti kadar böler 

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [37]:
arr=np.array([1.2, 2.3, 3.4, 4.5, 5.6], dtype=np.int8)#kayıplı tip dönüşümü söz konusu

In [36]:
arr

array([1, 2, 3, 4, 5], dtype=int8)

In [38]:
arr=np.array([1,2,3,4,5],dtype=np.complex128)

In [39]:
arr

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [40]:
#array metotları